<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'seotoolset' => '/class-seotoolset.php',
                'seotoolset_admin_menu' => '/class-seotoolset-admin-menu.php',
                'seotoolset_admin_meta_boxes' => '/class-seotoolset-admin-meta-boxes.php',
                'seotoolsetapi' => '/class-seotoolsetapi.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
